import type { Metadata } from "next";
import "./globals.css";
import Header from "./layout/Header";
import { Titillium_Web } from '@next/font/google';

const titilliumWeb = Titillium_Web({
  subsets: ['latin'],
  weight: ['200', '300', '400', '600', '700', '900'],
  variable: '--font-titillium-web',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${titilliumWeb.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
